require('./dbTest.js');
require('./signupTest.js');
require('./loginTest.js');
require('./createtripTest.js')
require('./acceptUserTest.js')
require('./rejectUserTest.js')
require('./joinTripTest.js');
require('./editTripTest.js');
require('./tripdetailsTest.js');
require('./mytripTest.js');
require('./getDisApprovedTest.js')
require('./removeJoinedTripTest.js')
require('./forgetPasswordTest.js')
require('./signoutTest.js');
